In [2]:
import numpy as np

Create exactly this 1D array:  
array([3, 14,  7, 21,  9])

In [138]:
arr_1 = np.array([3, 14,  7, 21,  9])
print(arr_1)

[ 3 14  7 21  9]


Create this evenly-spaced 1D array:  
array([  0,   5,  10,  15,  20,  25])

Allocate an uninitialized block of memory for a (4, 3) array — the fastest possible allocation. You will fill every cell before reading it.

In [136]:
arr_2 = np.empty((4,3))
print(arr_2)

[[0.0e+000 4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323 2.5e-323]
 [0.0e+000 0.0e+000 0.0e+000]
 [0.0e+000 0.0e+000 0.0e+000]]


In [6]:
arr_3 = np.arange(0, 30, 5)
print(arr_3)

[ 0  5 10 15 20 25]


Create this 2D matrix:   
array([[1., 1., 1., 1., 1.],  
       [1., 1., 1., 1., 1.]])

In [42]:
arr_4 = np.ones((2, 5), dtype = float)
print(arr_4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Create a random float array of this exact shape. Your values will differ — that is expected!  
array([[0.37, 0.95, 0.73],  
       [0.60, 0.16, 0.06],  
       [0.84, 0.22, 0.48]])

In [52]:
arr_5 = np.random.random((3, 3))
print(arr_5.round(2))

[[0.3  0.28 0.04]
 [0.61 0.5  0.05]
 [0.28 0.91 0.24]]


Create this identity matrix:  
array([[1., 0., 0., 0.],  
       [0., 1., 0., 0.],  
       [0., 0., 1., 0.],  
       [0., 0., 0., 1.]])

In [3]:
arr_6 = np.eye(4)
print(arr_6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Create this 2D matrix:  
array([[0., 0., 0., 0.],  
       [0., 0., 0., 0.],  
       [0., 0., 0., 0.]])

In [81]:
arr_7 = np.zeros((4, 4))
print(arr_7)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Create this array of exactly 5 evenly-spaced values:  
array([0.  , 0.25, 0.5 , 0.75, 1.  ])


In [92]:
arr_8 = np.linspace(0, 1, 5)
print(arr_8)

[0.   0.25 0.5  0.75 1.  ]


Create a random integer array of this shape with values in [1, 10). Your values will differ!  
array([[4, 9, 2, 7, 1],  
       [8, 5, 3, 6, 4]])

In [98]:
arr_9 = np.random.randint(1, 10, size=(2, 5))
print(arr_9)

[[6 8 1 8 4]
 [1 8 4 6 8]]


Create this constant-filled 2D matrix:  
array([[9, 9, 9],  
       [9, 9, 9],  
       [9, 9, 9]])

In [133]:
arr_10 = np.full((3, 3), 9)
print(arr_10)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [13]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(5, 4))
print(arr)
print('arg_max', arr.argmax())
# write code here to print the row + col number?

[[51 92 14 71]
 [60 20 82 86]
 [74 74 87 99]
 [23  2 21 52]
 [ 1 87 29 37]]
arg_max 11


In [25]:
row = arr.argmax() // arr.shape[1] +1
column = arr.argmax() % arr.shape[1] +1
print(f'row: {row} , column: {column}')
print(arr.shape[1])

row: 3 , column: 4
4


In [34]:
arr = np.random.randint(0, 100, size=(6, 3))
print(arr)
print('arg_max', arr.argmax())
row = arr.argmax() // arr.shape[1] +1
column = arr.argmax() % arr.shape[1] +1
print(f'row: {row} , column: {column}')
print(arr.shape[1])


[[22 14 42]
 [28 35 12]
 [31 70 58]
 [85 27 65]
 [41 44 61]
 [56  5 27]]
arg_max 9
row: 4 , column: 1
3
